### ISSUE TITLE
Polygons with existig bounding box can't be used to create a PolygonLayer with polygonCulling [BUG] 

### ISSUE THREAD

**Issue by dkuemper** [fleaflet/flutter_map#1428] opened 2023-01-04 14:05 UTC
### What is the bug?

If you use a `Listy<Polygon>` to inititalize a new PolygonLayer with `PolygonLayerOptions(polygons: widget.baseAreas, polygonCulling: true)` the constructor tries to calculate and assign new `polygon.boungingBox`, which is not possible since it is a `late final` initialized variable )can only be assigned once. 

```
  PolygonLayerOptions({
    Key? key,
    this.polygons = const [],
    this.polygonCulling = false,
    Stream<void>? rebuild,
  }) : super(key: key, rebuild: rebuild) {
    if (polygonCulling) {
      for (final polygon in polygons) {
        polygon.boundingBox = LatLngBounds.fromPoints(polygon.points);
      }
    }
  }
```

and

```
class Polygon {
  final List<LatLng> points;
  final List<Offset> offsets = [];
  final List<List<LatLng>>? holePointsList;
  final List<List<Offset>>? holeOffsetsList;
  final Color color;
  final double borderStrokeWidth;
  final Color borderColor;
  final bool disableHolesBorder;
  final bool isDotted;
  final bool isFilled;
  late final LatLngBounds boundingBox;
```

It is a very nasty error, since it only happens at runtime. 

### What is the expected behaviour?

Either way, the polygon bounding box shoul be abled to be assigned multiple times or the `PolygonLayerOptions` should only try to assign a new boundingBox if `polygon.boundingBox` ha previously previously null.

### Do you have a potential solution?

Fix `PolygonLayerOptions`:

```
class PolygonLayerOptions extends LayerOptions {
  final List<Polygon> polygons;
  final bool polygonCulling;

  /// screen space culling of polygons based on bounding box
  PolygonLayerOptions({
    Key? key,
    this.polygons = const [],
    this.polygonCulling = false,
    Stream<void>? rebuild,
  }) : super(key: key, rebuild: rebuild) {
    if (polygonCulling) {
      for (final polygon in polygons) {
        if(polygon.boundingBox!=null){
          polygon.boundingBox = LatLngBounds.fromPoints(polygon.points);
        }
      }
    }
  }
}
```

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux

### Severity

Fatal: Causes the application to crash

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JaffaKetchup** [comment] 2023-01-04 14:09
Hi @dkuemper, it looks like you're on an older version of this library, for which we cannot offer support. Please upgrade, and let us know if the issue persists. Thanks for reporting!

**Comment by JaffaKetchup** [comment] 2023-01-04 14:19
Ok, thanks. I'll tag this as non-fatal, as an error like this won't fully crash the app, it will just cause an error.

**Comment by fryette** [comment] 2023-03-09 11:13
It will just stop rendering Layer)
So it's crash

**Comment by JaffaKetchup** [comment] 2023-06-04 20:35
I'm closing this, as we haven't had other reports, and things have changed since. If this is still reproducible, please open a new issue with an MRE for the latest version!

**Closed by JaffaKetchup** 2023-06-04 20:35 UTC
Labels: bug, non-fatal
