### ISSUE TITLE
[BUG] Constraint and Fit inside bound with same value causes Red Screen

### ISSUE THREAD

**Issue by IcyTempest** [fleaflet/flutter_map#1920] opened 2024-06-23 05:48 UTC
### What is the bug?

Give When giving `CameraConstraint.contain` and `CameraFit.insideBounds` the same `LatLngBounds`. It causes errors, `MapCamera is no longer within the cameraConstraint after an option change`. Older version is fine (6.1.0)

Flutter map: 7.0.1
Flutter: 3.22.2

### How can we reproduce it?

This happen immediately after first rendering of the screen. No value changes need to trigger this error. Just the same Bounds vvalue to the fit inside bounds and cameraConstraint contain.

### Do you have a potential solution?

A temporary solution I found after abit more testing is that I have to include a `initialCenter` `LatLng` that is somwhere inside the contain coordinate to not trigger the assert.

### Platforms

Android 14 (Pixel 5)

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment] 2024-06-23 09:42
Hi @IcyTempest,
Thanks for the report. This is a duplicate of #1760, but includes some more useful info.

**Closed by JaffaKetchup** 2024-06-23 09:42 UTC
Labels: bug, needs triage
