### ISSUE TITLE
Replace deprecated library `latlong`

### ISSUE THREAD

**Issue by danilocubos** [fleaflet/flutter_map#852] opened 2021-03-24 18:39 UTC
Updating my project's libraries, I found the following incompatibility. The problem is that `latlong`, which is causing the incompatibility, is deprecated. Is it possible to replace it or even implement its functions directly on flutter_map, resolving this dependencies issue? Can I help you with it?

```
Because no versions of flutter_map match >0.12.0 <0.13.0 and flutter_map 0.12.0 depends on latlong ^0.6.1, flutter_map ^0.12.0 requires latlong ^0.6.1.

And because no versions of latlong match >0.6.1 <0.7.0 and latlong 0.6.1 depends on logging >=0.11.3 <1.0.0, flutter_map ^0.12.0 requires logging >=0.11.3 <1.0.0.

And because moor_generator >=4.2.0 depends on build ^2.0.0 which depends on logging ^1.0.0, flutter_map ^0.12.0 is incompatible with moor_generator >=4.2.0.

So, because my_project depends on both flutter_map ^0.12.0 and moor_generator ^4.2.1, version solving failed.
```

**Comment by Ratatinator97** [comment] 2021-03-26 08:48
https://pub.dev/packages/latlong2

**Comment by johnpryan** [comment] 2021-03-28 02:04
duplicate of https://github.com/fleaflet/flutter_map/issues/485

**Closed by johnpryan** 2021-03-28 02:04 UTC
