### ISSUE TITLE
[kml support] <kml support>

### ISSUE THREAD

**Issue by dasaki-gr** [fleaflet/flutter_map#1868] opened 2024-04-09 17:29 UTC
### What do you want implemented?

Is any support for KML file integration

### Severity

Obtrusive: No workarounds are available, and this is essential to me

**Comment by josxha** [comment] 2024-04-09 20:01
duplicate of https://github.com/fleaflet/flutter_map/issues/1790

**Closed by josxha** 2024-04-09 20:01 UTC
Labels: feature
