### ISSUE TITLE
I am working with Geoserver map in flutter using WMS layer. When i zoom in the map then some time it displays blurred map and app closes. what could be the issue? i mean when it takes more time than usual for loading map then it crashes the application after some time Why ?

### ISSUE THREAD

**Issue by UsamaAndroid** [fleaflet/flutter_map#1162] opened 2022-02-16 08:14 UTC
Verification of void com.google.android.gms.common.api.internal.zacp.() took 123.523ms or Skipped 161 frames! The application may be doing too much work on its main thread. before app crashes andoid studio shows one of these but mostly it gives me skipped frames error in run window of android studio and finally app crashes. sorry previuos question was accidently closed by me. but this issue is still not solved

**Comment by JaffaKetchup** [comment] 2022-02-16 08:18
Duplicate of #1161

**Closed** 2022-02-16 08:18 UTC
Labels: bug, needs verification
