### ISSUE TITLE
Error on _network_image_io.dart

### ISSUE THREAD

**Issue by kttary** [fleaflet/flutter_map#1284] opened 2022-06-21 05:50 UTC
I add a WMTS base map tile and flutter map ramdomly throw _network_image_io.dart (lines 121: rethrow). The exception message is HTTP request failed, statusCode: 404, https://xxx/webmercator/5/25/14.png. The tile 5/25/14.png does exists on the server. Another time it throw another error, Connection closed while receiving data. What could be causing this problem and how to skip this error by just showing an empty tile image for example?

**Comment by JaffaKetchup** [comment] 2022-06-21 06:06
As @ibrierley said, 404 is the Not Found HTTP error code.
Can you guarantee the image you are requesting actually exists? Try opening the erroring tile in a browser by typing in the URL

**Comment by kttary** [comment] 2022-06-21 08:31
i did open the erroring image via browser and it returning the single image on my browser. any options to pass the error without throwing an error?

**Comment by kttary** [comment] 2022-06-21 09:59
> i did open the erroring image via browser and it returning the single image on my browser. any options to pass the error without throwing an error?
![tile](https://user-images.githubusercontent.com/39557649/174773142-e1168ae8-8b3c-4904-8931-6d15a027a316.png)

**Comment by JaffaKetchup** [comment] 2022-06-21 10:44
I'd recommend using the DevTools (network tab) to see what requests are actually made and check those.

**Comment by JaffaKetchup** [comment] 2022-06-23 16:40
Closing this now, as I'm pretty sure it's not a bug in flutter_map. Hope you found a solution!

**Closed by JaffaKetchup** 2022-06-23 16:40 UTC
Labels: bug, needs verification

**Comment by kttary** [comment] 2022-07-03 03:16
I think this is because poor connection or wms my server performance, sometime it is not deliver the image timely and produce the error. Back to my question, is it possible to just return a blank image for example in case this error occur? I think my problem similar to [#1203](https://github.com/fleaflet/flutter_map/issues/1203)

**Comment by JaffaKetchup** [comment] 2022-07-03 10:14
@kttary You may be able to use the `errorImage` parameter in `TileLayerOptions`? #1203 will have to wait a while, as it's low priority as a feature request.

**Comment by vrman** [comment] 2023-06-01 23:39
same problem here , its ok on version 2 , but i got this error message after update package to version 4, any solution for fixing this problem ?
