### ISSUE TITLE
[BUG] Web browser on Android detects multi finger gesture after tile loading

### ISSUE THREAD

**Issue by cordierben** [fleaflet/flutter_map#1583] opened 2023-07-11 09:42 UTC
### What is the bug?

* Bug

Using Chrome on an Android device, once you move and reach a tile not loaded, the move becomes a zoom, and thus it is nearly impossible to move correctly. This occurs only the first time since tiles are loaded then. It seems to be caused by the short lag created by the tile loading : once the tile is loaded, the map still detect an input (finger) and thus when trying to move, a zoom is executed since it detects two fingers.

https://github.com/fleaflet/flutter_map/assets/61388583/0deb8caf-323e-4e02-be91-9d8ab08fa3db

* Code

This is my piece of code for MapOptions : 

```
MapOptions(
        onMapReady: _onMapReady,
        center: config.defaultCoordinates,
        zoom: mapParameters.defaultZoom,
        maxBounds:
            LatLngBounds(MapConstants.mapLimitsInf, MapConstants.mapLimitsSup),
        interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate,
        onTap: _onTapMap,
        onPositionChanged: ((position, hasGesture) {"some logic"})
);
```

I am using MapBox to load tiles.
The map is contained inside an iframe.

* Versions : 

Flutter map v4, but it seems like the issue is still present in v5
Flutter (Channel stable, 3.7.12, on macOS 13.2 22D49 darwin-arm64, locale fr-FR)

### How can we reproduce it?

The bug can be reproduced by running a project with the map on web, and loading it on an Android device

### Do you have a potential solution?

No workaround found since I don't want to disable pinchzoom.

### Platforms

Web browser (any browser, any version) on Android

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by rorystephenson** [comment] 2023-07-13 16:55
Hi @cordierben, can you confirm that this still occurs when maxBounds is not set?

**Comment by cordierben** [comment] 2023-08-04 14:40
Yes I can confirm it, when I remove maxBounds, it still occurs. It seems like the map consider that the finger il still on the screen when there is a small lag (onPointerDown is still called), and thus when I press a second time, it zooms

**Comment by JaffaKetchup** [comment] 2023-08-14 20:17
Hi @cordierben,
I'm struggling to reproduce this with the latest example web app from 'master' (https://demo.fleaflet.dev), on my Android (MIUI 14/Android 13) in Chrome, on either the main/landing page or the slightly slower loading WMS page.

**Comment by JaffaKetchup** [comment] 2023-08-14 20:19
Is it possible that the IFrame may be causing issues?

**Comment by JaffaKetchup** [comment] 2023-08-26 15:55
I'm going to close this for now, as I'm unable to reproduce. If you can provide a full MRE, please ping me to re-open!

**Closed by JaffaKetchup** 2023-08-26 15:55 UTC
Labels: bug, needs triage
