### ISSUE TITLE
Repository Package latlong is archived

### ISSUE THREAD

**Issue by komape** [fleaflet/flutter_map#678] opened 2020-07-06 15:39 UTC
As the [GitHub page](https://github.com/MikeMitterer/dart-latlong) for `latlong` states, the package is deprecated and will not be maintained anymore. Seems like they compiled the code to JavaScript to use it as npm package. Now they use TypeScript and gave up Dart.

Are there any plans to deal with this? I could take care about a fork of the repository to make sure, the package is available in the future. Please contact me, if required.

**Comment by johnpryan** [comment] 2020-07-09 18:18
dupe of https://github.com/fleaflet/flutter_map/issues/485

**Closed by johnpryan** 2020-07-09 18:18 UTC
