### ISSUE TITLE
I can not to update http library in latest version 1.0.0

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [fleaflet/flutter_map#1533] opened 2023-05-29 07:17 UTC
### What is the bug?

Can’t update htpp library in the latest version 1.0.0 because flutter_map 4.0.0 depends on http ^0.13.6

Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 3.0.2 • DevTools 2.23.1

### How can we reproduce it?

just upgrade http library 

### Platforms

android and ios

### Severity

Minimum: Allows normal functioning

**Comment by mpastorino1** [comment] 2023-05-29 08:39
I've the same problem.

**Comment by JaffaKetchup** [comment] 2023-05-29 09:17
Duplicate of #1531

**Comment by JaffaKetchup** [comment] 2023-05-29 09:17
Please use the 'master' branch.

**Closed** 2023-05-29 09:18 UTC
Labels: bug, duplicate
