### ISSUE TITLE
lastrotation lateinitialization error

### ISSUE THREAD

**Issue by MichalNemec** [fleaflet/flutter_map#924] opened 2021-06-07 14:42 UTC
Hello,
fresh flutter 2.2.1
included map as a simple stateless widget which is used in homepage.
When i click and drag it goes all over the place and showing just
`
════════ Exception caught by gesture ═══════════════════════════════════════════
LateInitializationError: Field '_lastRotation@627256441' has already been initialized.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
LateInitializationError: Field '_lastRotation@627256441' has already been initialized.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════

`

**Comment by kengu** [comment] 2021-06-07 14:45
Duplicate of #922

**Comment by kengu** [comment] 2021-06-07 14:45
Fix is merged to master, @johnpryan will hopefully release 0.14.0 to pub.dev soon.

**Closed by kengu** 2021-06-07 14:45 UTC
Labels: duplicate

**Comment by kengu** [comment] 2021-06-07 17:44
Version 0.13.1 is released to pub.dev with hotfix #923
