### ISSUE TITLE
Late Initialization Error

### ISSUE THREAD

**Issue by afshinshahriarifahliani** [fleaflet/flutter_map#1290] opened 2022-06-28 00:30 UTC
LateInitializationError: Field '_state@#########' has already been initialized.
This happen when I use it in a listview while scrolling down and then up the list.
So by changing the "late final MapState _state;" not to be final the error is gone.

**Comment by JaffaKetchup** [comment] 2022-06-28 20:31
Hi there @afshinshahriarifahliani,

This is a duplicate of #1288.

In the future, please check for duplicates before you raise an issue. Additionally, please use the appropriate issue template: it makes it easier for us to understand and respond quicker!

Thanks for the report.

**Closed by JaffaKetchup** 2022-06-28 20:31 UTC
