### ISSUE TITLE
[BUG] Linux + Firefox: Right click breaks future left click/drag events

### ISSUE THREAD

**Issue by lonelyteapot** [fleaflet/flutter_map#1644] opened 2023-09-08 01:44 UTC
### What is the bug?

After right clicking once, the map gets permanently stuck in a state where it cannot be dragged. On left click, instead of moving, it behaves as if the user was performing a pitch&zoom gesture.

The only fix I found is to reload the page.

### How can we reproduce it?

- Visit [the live demo](https://demo.fleaflet.dev/) in Firefox on a Desktop
- Move the map using the mouse
- Right click anywhere
- Try to move the map again

### Platforms

Web (Firefox; X11; Linux x64)

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment] 2023-09-19 16:24
Unfortunately, I'm unable to reproduce on my Windows (64-bit) machine running Firefox 118.0b9 beta. I can't test on Linux right now, but I find it unlikely that the behaviour will be much different between the same browser on different OSs. For the record, I also couldn't reproduce with Chrome 118.0.5993.11 dev.

Please ping for this to be reopened if you're sure the issue only affects Linux.

**Comment by lonelyteapot** [comment] 2023-09-19 20:45
I've tested again on a clean installation of the same Firefox version (118.0b9).
The issue persists.

Here's a clip of moving the map holding left click:

https://github.com/fleaflet/flutter_map/assets/50505104/c3fc8103-bc3e-490d-94fd-a96137f2dc31

And here is Troubleshooting Information from Firefox just in case: https://pastebin.com/UpQRhUzr

Unfortunately, I don't have any other other desktop machines right now. This one is a pretty standard installation of Endeavour OS (Arch btw).

**Comment by lonelyteapot** [comment] 2023-09-19 23:39
> How do you close the right-click context menu? I'm assuming a simple left click off of it?

Yes

> I have an Ubuntu dual boot that I should be able to check tomorrow

Thanks!

**Comment by joosakle** [comment] 2023-09-20 06:43
I can reproduce this on RHEL8, using Firefox 102.15.0esr. No right-click issue with other browsers.

**Comment by JaffaKetchup** [comment] 2023-09-20 17:03
Indeed, I can also reproduce this on my Ubuntu distro with Firefox.

Could this issue be in Flutter, or even Firefox?

**Comment by JaffaKetchup** [comment] 2023-09-25 16:29
I'm marking this as blocked, as I can't think how we should be doing anything differently here.

**Comment by mootw** [comment] 2023-10-15 22:06
i can also confirm that i can reproduce this issue on arch linux + firefox. i do not see this issue on chrome. my guess is that this is a flutter+firefox issue? i cannot see how our gesture handling would cause that to happen. commenting so im subscribed and might eventually take a look at this.

**Comment by JaffaKetchup** [comment] 2023-10-20 17:22
Someone should probably report this to Flutter. Or even Mozilla, if the difference between that and Chromium is unintended.
I'll try to do it soon if I remember, but someone else feel free to!

**Comment by JaffaKetchup** [comment] 2023-12-10 18:08
We're closing this for now, as this seems to be an external issue.

**Closed by JaffaKetchup** 2023-12-10 18:08 UTC
Labels: bug, P: 2 (soon™?), external, S: core
