### ISSUE TITLE
[BUG] Zooming with double tap + drag doesn't reload the tiles

### ISSUE THREAD

**Issue by josxha** [fleaflet/flutter_map#1633] opened 2023-08-30 15:42 UTC
### What is the bug?

The double tap - drag gesture does not reload the tiles. You need to do another gesture to trigger the loading of new tiles.
Tested with the latest v6 pre-release.

https://github.com/fleaflet/flutter_map/assets/34318751/8cebf649-64dc-46ea-89c2-0c9450c5dd49

### How can we reproduce it?

1. Open the demo application and navigate to the "Interactive Flags" screen.
2. Activate the "Double tap" and "+ drag" gestures.
3. Zoom in or out into another zoom level.

### Platforms

all platforms

### Severity

Minimum: Allows normal functioning

**Comment by JaffaKetchup** [comment] 2023-08-30 15:43
Duplicate of #1602

**Closed** 2023-08-30 15:43 UTC
Labels: bug, needs triage
