### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by kamilratulowski** [fleaflet/flutter_map#1146] opened 2022-02-01 09:15 UTC
Can anyone tell me what i did wrong?
This is the problem:
The relevant error-causing widget was FlutterMap
RangeError (index): Invalid value: Valid value range is empty: 0

```
import 'package:flutter/material.dart';

import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class DataScreen extends StatelessWidget {
  DataScreen({Key? key}) : super(key: key);
  static const routeName = '/data-screen';
  final markers = <Marker>[];

  void addMarker() {
    Marker marker = Marker(
      point: LatLng(49.23175824, 19.98163184),
      builder: (ctx) => const Icon(Icons.menu),
    );
    markers.add(marker);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          FlutterMap(
            options: MapOptions(
              center: LatLng(49.2849, 19.9732),
            ),
            layers: [
              TileLayerOptions(
                  urlTemplate:
                      'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                  subdomains: ['a', 'b', 'b'],
                  fastReplace: true),
              MarkerLayerOptions(
                markers: markers,
              )
            ],
          ),
          Positioned(
            top: 30,
            left: 50,
            child: InkWell(
              onTap: () {
                addMarker();
              },
              child: const Text('PRESS'),
            ),
          )
        ],
      ),
    );
  }
}
```

**Comment by ibrierley** [comment] 2022-02-01 09:23
Is there a specific line it points to with the error ?

**Comment by kamilratulowski** [comment] 2022-02-01 09:29
> Is there a specific line it points to with the error ?
> 

24 FlutterMap()

**Comment by kamilratulowski** [comment] 2022-02-01 10:15
> Is there a specific line it points to with the error ?
> 
When i start scrolling on the screen everything is ok

**Comment by kamilratulowski** [comment] 2022-02-01 10:19
Uploading SVID_20220201_111847_1.mp4 …

**Comment by kamilratulowski** [comment] 2022-02-01 10:24
Uploading SVID_20220201_111847_1.mp4

**Comment by ibrierley** [comment] 2022-02-01 10:28
Bit technical, just in case someone else reads as well and has some ideas, as I'm a bit tied up atm, but may get chance to have a better look later..

A quick rummage...(so may be off target)

I think there's a bug in FlutterMaps MarkerLayer, where it barfs if the pxCache has a different number of markers to the actual number markers. So I think this may happen a lot in cases where people add new markers...

I note we regenerate pxCache if didUpdateWidget is called or the zoom changes...maybe it needs to also be called if px cache size is different to marker list size as well....

Suggestion for fluttermap bug fix.
```
if(widget.markerLayerOptions.markers.length != _pxCache.length) {
          _pxCache = generatePxCache();
}
```

**Comment by ibrierley** [comment] 2022-02-01 12:35
so, just thinking out loud on this a bit more.

Let's assume someone may have 10,000 markers, projections internally cached, not in view, and they change the last marker LatLng which makes it now come in view. What should happen ?

A length check (which I think would fix the crash and maybe ok as a very temp solution), wouldn't help here. So what are the options ?

0) Don't have caching

1) rescan every Marker to see if it's changed. Probably more optimal than recalculating projections every go, but I assume some performance downside.

2) Give the user the option to use the cache or not, with clear docs explaining issues.

3) Some dark magic to store if its added/deleted to (not sure if this is possible and make it easy to user. I think LatLngs have to be created and can't be mutated, but I may be out of touch on that)

4) Have 2 widgets, a MarkerLayer and a CachedMarkerLayer

Not sure I like any of those :D, anyone else have any ideas (or am I missing something and the issue is wrong)?

**Comment by ibrierley** [comment] 2022-02-02 20:47
There's a PR at https://github.com/fleaflet/flutter_map/pull/1147 to get around the problem if you wanted a test. Digging into it a bit more, you may be able to scrape by without the crash and PR by calling a setState({}) after you add the marker (which is probably wise anyway to update the display).

**Comment by ibrierley** [comment] 2022-03-04 19:23
Going to close this, but feel free to reopen if #1147 doesn't fix the problem for you.

**Closed by ibrierley** 2022-03-04 19:23 UTC
Labels: bug, non-fatal
