### ISSUE TITLE
windows desktop not supported 

### ISSUE THREAD

**Issue by yuanmaio** [fleaflet/flutter_map#1784] opened 2023-12-22 12:16 UTC
### What is the bug?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/4feb7d87-8bb0-487b-9851-9f15e7f7b1ea)

### How can we reproduce it?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/7cb9d42d-6d9b-411a-a4c8-c2fd694784e9)

### Do you have a potential solution?

![image](https://github.com/fleaflet/flutter_map/assets/8166762/3de6fc5a-e3d9-4e11-9b70-f9e9ade4f847)

### Platforms

windows 11

### Severity

Minimum: Allows normal functioning

**Comment by TesteurManiak** [comment] 2023-12-22 13:22
Duplicate of #1783 

As said by @JaffaKetchup we supports all platforms, if you are able to provide a minimal reproducible example please re-open the original issue instead of opening new ones.

**Comment by JaffaKetchup** [comment] 2023-12-22 13:25
It looks like you are potentially using a different library. We do not have any similar string in our code

**Closed** 2023-12-22 13:25 UTC
Labels: bug, duplicate, invalid, S: example
