### ISSUE TITLE
[BUG] After changing zoom and loading new level of tiles, previous level still at the screen, while you idleing

### ISSUE THREAD

**Issue by CartianFrei** [fleaflet/flutter_map#1961] opened 2024-09-12 07:47 UTC
### What is the bug?

This bug only works for one layer with urlTemplate: "https://core-renderer-tiles.maps.yandex.net/tiles?l=skl&v=24.08.30-0-b240902091900&x={x}&y={y}&z={z}&scale=1&lang=ru_RU&projection=web_mercator"
That's the mystery cause at the web application with the same link everything is fine;
Another layers from "maps-yandex" and our own services is working fine, but this one has problem like that:
After changing zoom and loading new level of tiles, previous level still at the screen with the new level of tiles, BUT!!! after moving map, or changin zoom a little bit, just for 1 pixel, previous layer is hiding, and everything looks nice, but map doesn't doin it automatically, so check this issue, please :)
![issue to flutter_map](https://github.com/user-attachments/assets/452bbd3e-2fa0-4c6a-9f9f-3c013c9da250)

### How can we reproduce it?

Only one thing that you need is try to build TileLayer with next urlTemplate:  "https://core-renderer-tiles.maps.yandex.net/tiles?l=skl&v=24.08.30-0-b240902091900&x={x}&y={y}&z={z}&scale=1&lang=ru_RU&projection=web_mercator". Then u have to try zoom it in/out and load new tiles. Do it without any other moves and You will face the problem :)

### Do you have a potential solution?

I dont know really, but one big hint is that bug works only for that link in my practice :C 

### Platforms

Samsung Galaxy A10 / Virtual device: Android 13.0 "Tiramisu"

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by CartianFrei** [comment] 2024-09-12 08:06
i found one more link with the same problem, look urlTemplate: "https://core-renderer-tiles.maps.yandex.net/tiles?l=skl&v=24.09.11-0-b240906182700&x={x}&y={y}&z={z}&scale=1&lang=ru_RU&client_id=yandex-web-maps&experimental_ranking_mode_name=default-web-ranking&auction=1&experimental_enable_direct_info_logging=1&use_permalinks_for_direct_requests=1&experimental_data_hd=vegetation_model_exp"

**Comment by CartianFrei** [comment] 2024-09-13 10:44
these two "problem" layers have something in common, they are only with names and roads, without "background" coverage...

**Comment by JaffaKetchup** [comment] 2024-09-13 12:49
This looks like a duplicate of #1837. The tiles are transparent, and FM doesn't prune tiles correctly after a zoom. Thanks for the extra info!

**Closed by JaffaKetchup** 2024-09-13 12:49 UTC
Labels: bug, duplicate

**Comment by corepuncher** [comment] 2024-10-18 01:40
This is the last "look and feel" issue left to fix for my project. 

That said, I"m not even sure how much faster you can make this happen compared to my method of waiting 32 ms after map has stopped moving. Unless you are able to somehow "pull the tablecloth" out from under the new tile as soon as it arrives.
