### ISSUE TITLE
Complex polylines and gradient issue

### ISSUE THREAD

**Issue by GaelleJoubert** [fleaflet/flutter_map#1124] opened 2022-01-12 10:21 UTC
Hello there, 
I'm drawing "complex" polylines with gradient, and stumble into a weird behavior !

By complex, I mean not a straight line at all, many points which can come back to the same area for exemple.

To be able to see the "begining" and "end" of the path, I am using a gradient of tree colors.
The idea is that the begining of the poyline is in one color, and slowly moove to another color the closer we are to the end.

**It's seems to work rather well for "simple" path, where the path don't go back near the begining. But for complex path, it looks like there is a "leaking" effect.** 

Here are some screenshots to explain more clearly what I'm getting :

**Picture 1** : A rather "simple path" that looks like what I wanted to acheive

![simplePath](https://user-images.githubusercontent.com/86407953/149121213-c99cdb79-7fc1-4b83-a437-aafc5de626c2.png)

**Picture 2** : A "complex" path, (which comes back near some of the begining points) with the "leaking effect" observed

![complexpath1](https://user-images.githubusercontent.com/86407953/149121205-7168d8c8-05e6-4fe0-9134-9b0a9ee9ee04.png)

**Picture 3** : Another "complex" path with a different "leaking effect" observed

![complexpath2](https://user-images.githubusercontent.com/86407953/149121208-79980d74-7aba-4d3e-865f-4b91c6e8b023.png)

Is this a bug, Or am I misunderstanding the way gradient works ? 
I just want to draw a line which as a begining in one color and the end in another. 
Can you help me ?

Here is the line of code I'm using to build the polyline :

`Polyline(points:_listPoint , strokeWidth: 3, gradientColors: [ colorGradient1,colorGradient5,colorGradient9, ], )`

Thank you very much !

**Comment by ibrierley** [comment] 2022-01-12 10:51
I _think_ this would be expected behaviour.

**Comment by GaelleJoubert** [comment] 2022-01-12 10:58
Mhhh ok.
Would you have any idea how to draw a complex polyline with a gradient like that :
 First points on the list are color 1 TO last points on the list are color 2 ?
 I don't want the gradient to be related to the GPS position of the points, but just their order in the list I provide.

I don't know if I'm being clear, but basically something that behave like my "Picture 1", even when the path looks like picture 2 or 3.

**Comment by GaelleJoubert** [comment] 2022-01-19 15:55
please ?

**Comment by bmason8** [comment] 2022-01-21 17:17
My only suggestion/guess would be to not use colors with `opacity` if you are. They'll mix when overlapping (or apparently even when close like in your image).

**Comment by ibrierley** [comment] 2022-03-04 19:26
I'm going to close this, as I'm not sure of a way this can be done. But feel free to open if still a problem.

**Closed by ibrierley** 2022-03-04 19:26 UTC
Labels: bug, question/help, non-fatal

**Comment by Naografix** [comment] 2024-10-03 15:16
Currently have the same issue here.
Do you have any solution to fix this?
![image](https://github.com/user-attachments/assets/a51b48ba-a791-448a-bf0e-0baeb26e9852)

**Comment by Naografix** [comment] 2024-10-03 15:17
Currently have the same issue here.
Do you have any solution to fix this?
![image](https://github.com/user-attachments/assets/40de4806-c9a3-4320-aaec-fde02fc8862e)

**Comment by JaffaKetchup** [comment] 2024-10-03 16:08
I'm not currently aware of a way to do this in Flutter. A quick Google search doesn't show anything. The reason this happens is because we essentially apply the gradient to the bounding box, not the line.

**Comment by christoph-linexo** [comment] 2025-07-01 07:01
Hello, thanks for creating this ticket. I currently have the same issue were I was surprised by this gradient leakage behavior. I also have the problem that when I have a closing route

<img width="138" alt="Image" src="https://github.com/user-attachments/assets/424bde07-11c4-46d2-95af-df8ac0ff597d" />

PseudoCode: 
```dart
FlutterMap(children: [PolylineLayer(polylines: [Polyline(points: points, gradientColors: [purple, yellow, yellow, yellow], colorStop: [0, 0.5, 0.9, 1])]]);
```

Thank you:)
