### ISSUE TITLE
[FEATURE] Fallback to higher/lower zoom level if unable to load tile

### ISSUE THREAD

**Issue by cwhitby** [fleaflet/flutter_map#1397] opened 2022-11-02 10:34 UTC
### What do you want implemented?

I'm using this in conjunction with [flutter_map_tile_caching](https://pub.dev/packages/flutter_map_tile_caching).

Currently, if I'm offline and have an area at zoom level 9 cached and I zoom in or out, the entire map disappears as the tiles at those zoom levels are unable to load. I would like to be able to continue to show scaled tiles from a higher or lower zoom level if tiles are unable to load.

This would also be beneficial to users without the flutter_map_tile_caching plugin if you are browsing the map and your map tiles fail to load due to a network error. Also useful if your tile provider does not provide tiles below a certain zoom level, this would continue to show higher tiles but scaled up (reduction in quality is expected).

### What other alternatives are available?

Leaflet has a [tile fallback plugin](https://github.com/ghybs/Leaflet.TileLayer.Fallback) that offers this.

### Platforms Affected

Android, iOS, Web, Windows, MacOS, Linux, Other

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by ibrierley** [comment] 2022-11-02 10:45
I think this makes sense. I guess one question is whether "best effort" to retrieve tile is good enough, or it has to be 100% reliable. I.e options 
1) Store the tiles manually and have control (not sure if this would work on web?).
2) Kind of assume any previously downloaded tile will be in the devices cache and it tries to load that ?
3) Others

(Is there a generic way to test if a file is in normal device cache ?)

Reminds me a bit of my "discussion" at https://github.com/fleaflet/flutter_map/discussions/1304 :D

**Comment by JaffaKetchup** [comment] 2022-11-02 15:35
I wonder if similar code can be reused from `maxNativeZoom` somehow?

**Comment by ibrierley** [comment] 2022-11-02 15:58
I'm not sure that would work ideally if we have useful tiles below or above the current zoom level (unless there was a max and min based on previous loads, but then those loads are going to be partial loads, so feels a bit fraught with potential issues ?

One thing I did with an old bit of vector code was try and simplify the tile code and address that issue, original at https://github.com/ibrierley/flutter_map_tile_layer_x/blob/master/lib/tile_layer_plugin.dart ) this was for an old version of flutter_map so can't simply plugin atm, but could be an idea as part of a larger tile rewrite we may do one day :D.


```
for (var j = miny; j <= maxy; j++) {
      for (var i = minx; i <= maxx; i++) {
        var coords = Coords(i.toDouble(), j.toDouble());
        coords.z = _tileZoom;

        if (!_isValidTile(coords)) {
          continue;
        }

        // Add all valid tiles to the queue on Flutter
        queue.add(coords);

        /// If a tile is outstanding still, or has never been loaded recently
        /// We'll try and look for other tiles on levels above/below, depending
        /// on our expansion strategy. Example of backupTileExpansionStrategy
        /// would be [1,2,3,-1] which means if we are zoom 14, we'll check 13,
        /// then 12, 11, then 15.
        if (_outstandingTileLoads.containsKey(_tileCoordsToKey(coords)) ||
            !_recentTilesCompleted.containsKey(_tileCoordsToKey(coords))) {
          Coords backupCoords;

          /// If we've found backuptiles, we don't want to pursue any more
          var haveBackup = false;

          /// This works by expanding on a power of 2, eg tile 32,11 covers
          /// 64,22 & 65,22 & 64,23 & 65, 23 in one direction, and 16,10 in going
          /// backwards. So if we've recently completed it, there's a good chance
          /// it's a the cache.
          options.backupTileExpansionStrategy.forEach((levelDifference) {
            var ratio = pow(2, levelDifference);

            /// If we need covering tiles from a higher zoom we may need
            /// several tiles to cover each 'larger' tile, extraTileFactor.
            if (!haveBackup) {
              var extraTileFactor = (1 / ratio).abs();

              for (var a = 0; a < extraTileFactor; a++) {
                for (var b = 0; b < extraTileFactor; b++) {
                  var backupZoom = _tileZoom - levelDifference;
                  if (backupZoom > options.maxZoom || backupZoom < 0) continue;

                  backupCoords = Coords(
                      (i ~/ ratio + a).toDouble(), (j ~/ ratio + b).toDouble());
                  backupCoords.z = backupZoom;

                  var tileKey = _tileCoordsToKey(backupCoords);

                  /// It shouldn't end up both completed && outstanding, but it
                  /// could be possible if was in cache but not any more...
                  if (_recentTilesCompleted.containsKey(tileKey) &&
                      !_outstandingTileLoads.containsKey(tileKey)) {
                    _backupTiles[tileKey] = TileX(backupCoords, false);
                    haveBackup = true;
                  }
                }
              }
            }
          });
        }
      }
    }
... // sort stuff in here

var allTilesToRender = backupTilesToRender + tilesToRender;

.. // create widgets etc here
.. // housekeeping
```

**Comment by JaffaKetchup** [comment] 2022-11-02 21:36
Sure, part of a larger tile rewrite sounds good. The `maxNativeZoom` was just a reference because it already does the same effect - even though it's for a very different use-case.
Just to note to readers, this is unlikely to happy soon, although we do discuss privately to some extent.

**Comment by cwhitby** [comment] 2022-11-09 14:22
Okay, glad to see this is at least on the roadmap for the future.

What's the possibility of some kind of workaround in the meantime? The app I'm working on has the majority of its users on horrendously slow satellite internet in the middle of the ocean and having the screen go completely blank while waiting for more tiles to download is a pretty significant issue for them.

**Comment by ibrierley** [comment] 2022-11-15 21:23
Have been thinking about this a bit more, it's a bit unclear really. 

The leaflet plugin mentioned earlier relies on an error, which is if the tile is unavailable due to a max tile zoom issue (probably, but not only), not a network error. If that plugin has no network connection, it won't work, as it can't try a lower zoom tile to load (it will also come up with a 404). So as @JaffaKetchup says maxNativeZoom may help there to avoid that problem in the first place.

If the tile is slow to download, there is a bit of code that will kick in to retain the parent/child zoom levels, so they shouldn't suddenly disappear.

So I think a bit of clarity is needed to understand the problem, you mention slow speeds, so I don't think a replica of the plugin would help at all, as it would just create more network retries and multiply the problem...sounds a bit more like you need a separate dynamic caching plugin based on a tile_provider or something in that direction, but I may be wrong, just thinking out loud.

**Comment by cwhitby** [comment] 2022-11-16 10:43
Happy to help clarify.

I'm not suggesting that the library should progressivly make more and more requests looking for a working tile. I'm suggesting that we only show the tiles we already have.

> If the tile is slow to download, there is a bit of code that will kick in to retain the parent/child zoom levels, so they shouldn't suddenly disappear.

This doesn't seem to be the case. If I load the app normally, the tile at the current zoom download and display. If I then disable the network and zoom in, the tiles immediatly disappear rather than scaling.

The scaling is what I'm after here. So regardless of whether there is slow speeds, no network at all, or some other tile loading error, I would like the existing tiles to scale.

**Comment by ibrierley** [comment] 2022-11-16 11:09
When you say "zoom in", do you mean manually with a panzoom, or with a mapController.move and zooming several different levels different to the current one ?

If you run the example Animated MapController and toggle between Paris and London, you should see it scaled. If in chrome you turn off the internet, you should see it still work "to a certain amount". I think there are limits though, of 5 levels for the parent zoomed tiles, and 2 for the child tiles.

If you don't think that's happening, it would be useful to have a reproducible set of steps as there could naturally be a bug.

It's a bit of a fiddly one to retain a lot of potential tiles though (eg what if they pan to the right and then left, should it reintroduce a previously seen one...). I think as mentioned that's probably more for a plugin if that's required.

**Comment by ibrierley** [comment] 2022-11-16 13:01
That was just to highlight it working when there is a connection to show it scaling (and it does that for me)..

However when I look at manual other cases, it does look a bit like it's not quite doing what I thought (I think Chrome may be keeping some images I cached earlier so maybe getting a different experience).

**Comment by ibrierley** [comment] 2022-11-16 14:02
Digging a bit more, I think there's a quirk in the code around image errors, so we need to ponder what's best as I didn't write the original code, so may be misunderstanding a bit the intention... in https://github.com/fleaflet/flutter_map/blob/master/lib/src/layer/tile_layer/tile_layer.dart

Currently if a tile gets an error (eg a 404), we actually set the tile to "active". I think the idea here is to be able to draw an error image in place of the tile, so it has to be "active".

If the tile is "active", it doesn't bother trying to find an alternative to scale.

One possible workaround could be something like the following in tile_layer.dart (feel free to try and add around like 685 say)

```
  void setTileActiveIfNoError(Tile? tile) {
    if(!tile!.loadError && widget.errorImage == null) {
      tile!.active = true;
    }
  }
```

And then lower down in _tileReady, whenever its set to active original lines 704 & 721), we call

``` setTileActiveIfNoError(tile); ``` instead of  ```tile.active = true;```

So the idea is, if we don't have an error image, we try and use a fallback scaled tile. This isn't quite ideal, I guess what we probably would want is to try and find a backup, and display an error tile if that isn't available, but then that gets a bit more complex.

Whatever, this is probably a breaking change, so needs a bit of thought and testing, especially for performance in case too many old tiles hang about, but I'd be interested if you were to try this and the general perception is its an improvement (I think it is personally, but we all have different use cases).
 
It's also not perfect, tiles may be missing if they were previously pruned, eg panned right then left, you'd have to zoom out/in to trick it into making them active again.....

**Comment by cwhitby** [comment] 2022-11-16 15:32
So I've had a play around with what you suggested above and the results are pretty good. Manually zooming in and out produces nicely scaled tiles.

Since we combine our implementation with the tile caching library the pruning issue is minimised. Zooming in and out fetches tiles from the cache without issue, but the panning does require a change in zoom before a tile is loaded as you say.

**Comment by ibrierley** [comment] 2022-11-16 16:52
Thanks for the feedback. 

I guess we could make it optional, "fallbackToScaledTileIfError" (bit of a mouthful, but feels like you know what it should aim to do) or something...I'm not entirely happy with it doesn't feel very concrete, but it feels like an option that could be desired and implented further as well...

Happy to hear others opinions on all of this. We've been considering a bit of a rewrite, but it's hard to know when/if that will happen, and what exactly is needed for it and whether to shove more stuff in there in the meantime or not :D ...

**Comment by JaffaKetchup** [comment] 2022-12-20 18:23
If we do a rewrite, this should definitley be a part of it. If it's simple enough to do now, and is unlikely to have negative side effects, I also think this would be suitable to add now.

**Comment by cwhitby** [comment] 2023-01-20 08:07
Not stale, please keep open

**Closed** 2023-12-10 18:17 UTC
Labels: feature, P: 3 (low)
