### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by Pepslee** [fleaflet/flutter_map#1364] opened 2022-09-17 11:58 UTC
### What do you want implemented?

Preload tiles around the bounds to prevent gray tiles appearing when panning

### Platforms Affected

Android

### Severity

Minimum: Not required for my use

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked for similar feature requests which may be duplicates

**Comment by JaffaKetchup** [comment] 2022-09-17 13:47
Duplicate of #1337.

**Closed by JaffaKetchup** 2022-09-17 13:47 UTC
Labels: enhancement
