### ISSUE TITLE
[QUESTION] How to draw polyline on the road?

### ISSUE THREAD

**Issue by mserkanguzel** [fleaflet/flutter_map#1159] opened 2022-02-10 15:05 UTC
![Screenshot_2022-02-10-17-00-55-784_com example researchandlearn](https://user-images.githubusercontent.com/61592374/153435249-770cd167-3f45-44ee-a07d-491646777a17.jpg)

I'm using Open Street Map

**Comment by JaffaKetchup** [comment] 2022-02-10 16:07
Duplicate of #461.

**Closed** 2022-02-13 07:53 UTC
Labels: duplicate, question/help
