### ISSUE TITLE
Tile boundaries visible at certain zoom levels

### ISSUE THREAD

**Issue by pmjobin** [fleaflet/flutter_map#1126] opened 2022-01-12 19:45 UTC
I built the demo app using Flutter 2.8.1 (desktop linux target) and I noticed that tile boundaries pop out as white lines at certain zoom levels while they are seamless at others.

![Screenshot from 2022-01-12 15-35-32](https://user-images.githubusercontent.com/1387411/149209616-a19bc571-f627-46cc-beaf-5a9ea51015a2.png)

**Comment by jiazeh** [comment] 2022-01-13 02:45
Same issue, and this issue only happens on Flutter 2.8.x and above..

**Comment by mohammedX6** [comment] 2022-01-14 06:58
+1

**Comment by DrNorton** [comment] 2022-01-17 14:34
+1

**Comment by ibrierley** [comment] 2022-01-17 14:46
Does this happen on mobile too, or just on desktop ?

**Comment by DrNorton** [comment] 2022-01-17 14:52
> Does this happen on mobile too, or just on desktop ?

On mobile too, but only with disabled rotation

**Comment by JaffaKetchup** [comment] 2022-01-17 15:45
This seems strange, and would be probably Flutter 2.8's fault, because I haven't seen this before.
Maybe the changelog will hold the answers?

**Comment by DrNorton** [comment] 2022-01-17 16:58
I think that located problem, if I delete Opacity widget in _AnimatedTileState

**Before**:

`   return Opacity(
      opacity: widget.tile.opacity,
      child: widget.tileBuilder == null
          ? tileWidget
          : widget.tileBuilder!(context, tileWidget, widget.tile),
    );`

**After**:

` return widget.tileBuilder == null
        ? tileWidget
        : widget.tileBuilder!(context, tileWidget, widget.tile);`

The problem is gone. There are no white lines.

And there are many opacity issues that were merged in [release notes](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-2.8.

**Comment by ibrierley** [comment] 2022-01-17 17:03
Good find, this url should work if anyone has problems with above url https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-2.8.0

**Comment by JaffaKetchup** [comment] 2022-03-11 07:04
Duplicate of #1156

**Closed** 2022-03-11 07:05 UTC
Labels: bug, duplicate, non-fatal

**Comment by mostafaac30** [comment] 2022-08-26 17:16
same
