### ISSUE TITLE
is there any plan to build 3D map?

### ISSUE THREAD

**Issue by tranice** [fleaflet/flutter_map#1508] opened 2023-05-09 14:33 UTC
### What do you want implemented?

to view map in 3d mode , just like this:  https://www.procedural.eu/map/

### What other alternatives are available?

procedural_gl.js can be nested in mobile WebView, but has some issues  and hard to share resources locally 

### Can you provide any other information?

procedural_gl.js   base on three.js , and there is dart version of three.js . is it possible to develop this feature on it ?

https://pub.dev/packages/three_dart

### Severity

Annoying: Currently have to use workarounds

**Comment by JaffaKetchup** [comment] 2023-05-09 14:43
Hi @tranice,

This is too technologically challenging to implement into core. There have been some attempts before, such as implementing a very basic tilt, but these had issues pretty much everywhere.

This is a duplicate of #220, duplicate of #1268, duplicate of #1121, and more.

If you're willing to create a plugin, we'd be happy to add it to our docs!

**Closed** 2023-05-09 14:43 UTC
Labels: enhancement
