### ISSUE TITLE
[BUG] Impeller: `OverlayImageLayer` disappears at some zoom levels

### ISSUE THREAD

**Issue by RajDonga09** [fleaflet/flutter_map#1781] opened 2023-12-20 05:41 UTC
Hello,

I hope this message finds you well. I am reaching out to report an issue that I encountered while using the flutter_map package, specifically version 6.1.0. I have created a video illustrating the problem, which you can view here: [map_issue.mp4.](https://github.com/fleaflet/flutter_map/assets/60914469/af850afb-b5f2-4628-865d-84597d27073a)

I utilized the OverlayImageLayer in a map, and I observed that the OverlayImage disappears when zooming in too much on iOS. This behaviour is not consistent with the expected functionality.

**Using like this in Code**
```
const RotatedOverlayImage(
                topLeftCorner: LatLng(53.377, -2.999),
                bottomLeftCorner: LatLng(52.503, -1.868),
                bottomRightCorner: LatLng(53.475, 0.275),
                opacity: 0.8,
                imageProvider: NetworkImage(
                    'https://images.pexels.com/photos/231009/pexels-photo-231009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=300&w=600'),
              ),
```

**Flutter Doctor:**
```
[!] Flutter (Channel stable, 3.10.5, on macOS 12.6 21G115 darwin-x64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Users/macchoice/fvm/versions/3.10.5
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/macchoice/fvm/versions/3.10.5. Consider adding /Users/macchoice/fvm/versions/3.10.5/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/macchoice/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/macchoice/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • Redmi Note 7 Pro (mobile)      • 6840903b                                 • android-arm64  • Android 10 (API 29)
    • iPhone X 15.2.1 Black (mobile) • 10c4c9813d61f537ffb1a003d5bb8d5414427fca • ios            • iOS 15.2.1 19C63
    • macOS (desktop)                • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)                   • chrome                                   • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

Thank you
Flutter Developer

### How can we reproduce it?

 [map_issue.mp4.](https://github.com/fleaflet/flutter_map/assets/60914469/af850afb-b5f2-4628-865d-84597d27073a)

For reproducing issues please refer to the attachment
Step 1. Add an Overlay Image in the Map using OverlayImageLayer
Step 2. Then zoom in the overlay image to maximum on the iOS device  
Step 3. While doing the same you will see the image disappear
Step 4. If you zoom out then the image will appear again

### Platforms

iOS 📲

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment] 2023-12-20 10:31
Hi @RajDonga09,
What happens if you disable Impeller when building?

**Comment by RajDonga09** [comment] 2023-12-21 10:56
> Hi @RajDonga09, What happens if you disable Impeller when building?

I added the below code to the `Info.plist` file, and now it is working properly🚀🚀, Thanks @JaffaKetchup

Also, here's another question, adding this code will not affect the existing functionality Right?

```
<key>FLTEnableImpeller</key>
<false/>
```

**Comment by JaffaKetchup** [comment] 2023-12-22 10:18
This is a duplicate of #1528. We thought this had been fixed - can you just confirm you are running the **latest** Flutter version?

Disabling Impeller will not directly affect app functionality except in a few rare edge cases, but it will lose the performance benefits it potentially brings.

**Comment by RajDonga09** [comment] 2023-12-26 05:00
Currently, I'm using Flutter 3.10.5 right now, and it functions perfectly 🙂.

We can close this ticket, I hope it will work properly in future without turning off the impeller.

Thank you for the feedback @JaffaKetchup

**Closed** 2023-12-26 09:21 UTC
Labels: bug, duplicate, external
