### ISSUE TITLE
Rotated map jumps around when panning

### ISSUE THREAD

**Issue by johnpryan** [fleaflet/flutter_map#361] opened 2019-07-16 17:54 UTC
The MapController sample allows rotation, but panning a rotated map causes the map to jump. This may be due to the fling animation.

See https://github.com/johnpryan/flutter_map/pull/359 for details related to rotation

**Comment by paolorotolo** [comment] 2019-08-13 15:06
I can still reproduce this on master, are you sure it's fixed?

**Comment by johnpryan** [comment] 2019-08-13 16:29
I'm not sure, I'll reopen this.

**Comment by paolorotolo** [comment] 2019-08-13 16:36
Woops, I already opened #387. If it's the same cause we can close it and continue here.

**Comment by paolorotolo** [comment] 2019-08-15 18:55
So this is the behavior I recorded on a Pixel 3: https://youtu.be/wEW-7ZECZrw

As you can see, only when the map is rotated, the panning animation isn't smooth and the map jumps down.

**Comment by paolorotolo** [comment] 2019-11-13 12:01
Any update on this?

**Comment by ibrierley** [comment] 2020-02-27 07:55
Not sure I can see this in master, but it would be good to be fixed, is it because the CI tests failed ? (not that familiar with it yet!)

**Comment by RomanJos** [comment] 2020-03-16 07:32
I also have this problem, setting the rotation to 180 and 0 have no problem though

**Comment by mat8854** [comment] 2020-04-26 18:41
Yes, it seems to be worst for rotation values of 90 and 270 degrees. We tried it too.

**Comment by maRci002** [comment] 2020-08-07 16:21
Hello, PR #719 fixes this problem.

**Closed** 2021-01-29 17:48 UTC
Labels: bug
