### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Henk-Keijzer** [fleaflet/flutter_map#1609] opened 2023-08-09 10:51 UTC
### What is the bug?

Clickable links in the rich attribution window are active also when the attribution window is not visible.

### How can we reproduce it?

      nonRotatedChildren: [
        RichAttributionWidget(
          popupBackgroundColor: Colors.white70,
          alignment: AttributionAlignment.bottomRight,
          showFlutterMapAttribution: false,
          permanentHeight: 32,
          attributions: [
            TextSourceAttribution(
              'Basiskaart: ${mapTileProviderData[selectedMapType]['attrib']}',
              textStyle: const TextStyle(color: Colors.black87),
              onTap: () => launchUrl(Uri.parse(mapTileProviderData[selectedMapType]['attribLink']),
                  mode: LaunchMode.platformDefault)
            ),
            (mapOverlay && overlayTileProviderData.isNotEmpty) ? TextSourceAttribution(
              'Kaartoverlay: ${overlayTileProviderData[selectedOverlayType]['attrib']}',
              textStyle: const TextStyle(color: Colors.black87),
              onTap: () => launchUrl(Uri.parse(overlayTileProviderData[selectedOverlayType]['attribLink']),
                mode: LaunchMode.platformDefault)
            ) : const TextSourceAttribution(''),
            TextSourceAttribution('2011-${DateFormat('yyyy').format(DateTime.now())} Stichting Zeilvaart Warmond',
              textStyle: const TextStyle(color: Colors.black87),
              onTap: () => launchUrl(Uri.parse('https://www.zeilvaartwarmond.nl'))
            )
          ],
        ),
      ],

### Do you have a potential solution?

No

### Platforms

tested on Windows, Android, Web

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment] 2023-08-09 11:45
Duplicate of #1589

**Comment by JaffaKetchup** [comment] 2023-08-09 11:46
Fixed by #1591, available on the master branch and v6 prereleases.

**Closed** 2023-08-09 11:45 UTC
Labels: bug, duplicate
