### ISSUE TITLE
[BUG] Gestures apparently less responsive after long press

### ISSUE THREAD

**Issue by Henk-Keijzer** [fleaflet/flutter_map#1695] opened 2023-10-19 09:27 UTC
### What is the bug?

clicks on the map work fine until a longpress on the map is triggered (and the function executed). After the longpress the map can still be moved around and zoomed in/out, but single clicks and longpresses do not result in the attached function to be called

### How can we reproduce it?

set up map with both single click and longpress functions defined. After a single click, subsequent click work, but once you do a longpress, the single click and longpress no loinger work

### Do you have a potential solution?

no

### Platforms

windows 11

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment] 2023-10-20 17:31
Also see #1581, which details the particular issues that occur on the web (may be outdated).

**Comment by josxha** [comment] 2023-11-02 09:50
Couldn't reproduce. Tested on Windows 11 and on Chrome on windows 11. 
- flutter 3.13.5 
- flutter_map 6.0.1
- windows 11
- chrome web browser

https://github.com/fleaflet/flutter_map/assets/34318751/dccefa62-c3ac-4ea6-bdc8-74fec9e4119e

**Comment by Henk-Keijzer** [comment] 2023-12-05 10:00
The problem persist, but only in the following circumstances:
- on web, Edge, Chrome etc.
- when the onPressed calls launchUrl (with or without async/await)

onLongPress: (_, latlng) async {
  if (eventStatus == 'live' || eventStatus == 'pre-event') {
    await launchUrl(Uri.parse('https://embed.windy.com/embed2.html?lat=${latlng.latitude}&lon=${latlng.longitude}'
        '&detailLat=${latlng.latitude}&detailLon=${latlng.longitude}'
'&width=$screenWidth&height=$screenHeight&zoom=11&level=surface&overlay=wind&product=ecmwf&menu=&message=true&marker='
'&calendar=now&pressure=&type=map&location=coordinates&detail=true&metricWind=bft&metricTemp=%C2%B0C&radarRange=-1'));
  }
}

It works on web in Edge on Android, but the first interaction with the map after coming back to the browser window with the map is irresponsive. 
It works fine on Android, iOS and on a Windows app.

**Comment by josxha** [comment] 2023-12-05 11:01
Thanks for the additional information. I was able to reproduce it now.

**Comment by josxha** [comment] 2023-12-09 12:47
@Henk-Keijzer I'm closing this issue because this issue is a general flutter web issue. 
I reported this issue to flutter in https://github.com/flutter/flutter/issues/139862.

As a workaround you could open an `AlertDialog` that promts the user something like "Do you want to open windy for this location? yes / no" on a long press and then call `launchUrl()`.

**Closed by josxha** 2023-12-09 12:47 UTC
Labels: bug
