### ISSUE TITLE
Replace "latlong: ^0.6.1" package as it is deprecated and not maintained.

### ISSUE THREAD

**Issue by Pinkal7600** [fleaflet/flutter_map#727] opened 2020-08-14 03:52 UTC
We should replace the `latlong: ^0.6.1` package as it is not maintained and have some limitation for latitude and longitude value. Like we can only provide latitude value between -90 to 90 and longitude value between -180 to 180. So this makes the limitation for flutter_map compare to leaflet as leaflet does not have this kind of restrictions. 

I personally face this issue(https://github.com/fleaflet/flutter_map/issues/725) in my one use case so I replace this package with `maps_toolkit: ^1.1.0+2` and make some modification in that as well to use the `math_util.dart` for flutter_map like `toRadians()`, `toDegrees()`, etc...

**Comment by pdenert** [comment] 2020-08-28 13:28
Could you make PR with your working solution? I think that author of this package will be glad of it, as this is a side project for him and he call for maintainers #680

**Comment by johnpryan** [comment] 2021-03-16 23:29
Duplicate of https://github.com/fleaflet/flutter_map/issues/485

**Closed by johnpryan** 2021-03-16 23:29 UTC
