### ISSUE TITLE
[BUG] Impeller causes `OverlayImageLayer` to disappear at some zoom levels

### ISSUE THREAD

**Issue by W2NJL** [fleaflet/flutter_map#1528] opened 2023-05-18 01:36 UTC
### What is the bug?

Please feel free to nuke this post if this was addressed in flutter_map v4, which I've not upgraded to yet because of a dependency.

I just updated to Flutter 3.10, the only aspect I can surmise different from prior, and my OverlayImageLayer will not show in my FlutterMap instances anytime I zoom in (or initialize Zoom) at level 10 or below.  If I zoom out beyond these levels, the overlay appears normal.  This had never been an issue prior.

I'm running flutter_map 3.1.0.

Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.1)
[✓] Connected device (3 available)
[✓] Network resources

### How can we reproduce it?

```
 MarkerLayer(markers: markers,),


          OverlayImageLayer(
            overlayImages: overlayImages,
          ),


          PolylineLayer(
            polylines: [ radioStation.distance <= 250 && radioLandSearchValues.showPolyline!
                ? Polyline(
              // An optional tag to distinguish polylines in callback
              points: linePoints,
              color: Colors.red,
              strokeWidth: 3.0,
            ):Polyline(points: []),

            ],

          ),
          MarkerLayer(markers: pinMarkers,),
```

### Platforms

Has occurred on both physical iPhone 14 Pro Max and iPhone 14 Pro Max Emulator

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by ibrierley** [comment] 2023-05-18 05:28
Is it possible to show a minimal reproducable example with the image etc for someone to test.

**Comment by W2NJL** [comment] 2023-05-18 15:33
Absolutely.  Here's a super basic deployment of FlutterMap where the issue happens.  I initialize the map at Zoom level 9.  As soon as I zoom in one level, the overlay disappears.

`FlutterMap(



        options: MapOptions(




            center:  LatLng(40, -74
                 ),
          zoom:
              9,
          interactiveFlags: InteractiveFlag.pinchZoom |
              InteractiveFlag.drag |
              InteractiveFlag.doubleTapZoom
        ),
        children: [





          TileLayer(

              urlTemplate:
              'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
              subdomains: [
                'a',
                'b',
                'c'
              ]),

          OverlayImageLayer(

              overlayImages: <OverlayImage>[OverlayImage(bounds: LatLngBounds(LatLng(38, -77), LatLng(42, -72)), opacity: 140,imageProvider: NetworkImage('https://i.ibb.co/371Qjyv/4b95d868037040e18ba4c1b6063ebeb7-0.png')),]
          ),

        ]);`

**Comment by JaffaKetchup** [comment] 2023-05-18 15:42
> `opacity: 140`

This seems a little off? Opacity is always between 0.0 and 1.0 AFAIK - but not sure if this will affect anything.

**Comment by W2NJL** [comment] 2023-05-18 15:49
> > `opacity: 140`
> 
> This seems a little off? Opacity is always between 0.0 and 1.0 AFAIK - but not sure if this will affect anything.

No idea why I have it at that level, either, but I just changed to a value of 1 and then 0.5 subsequently, and the issue persists.

**Comment by ibrierley** [comment] 2023-05-18 16:49
Hi, have just tested the example and the image overlay stays on from zoom 0 to whatever the maximum zoom is (prob 19 or so), so it all works for me (sorry, thats annoying I know!).

I have tested both on Web and Linux desktop.

**Comment by W2NJL** [comment] 2023-05-18 16:51
> Hi, have just tested the example and the image overlay stays on from zoom 0 to whatever the maximum zoom is (prob 19 or so), so it all works for me (sorry, thats annoying I know!).
> 
> I have tested both on Web and Linux desktop.

OK, then whatever it is is with my environment, I appreciate it.  Can I just ask what Flutter version you are on?

**Comment by ibrierley** [comment] 2023-05-18 16:53
I was testing with
```
Dart SDK 3.0.0
Flutter SDK 3.10.0
flutter_map 3.2.0
```

**Comment by W2NJL** [comment] 2023-05-18 17:15
> I was testing with
> 
> ```
> Dart SDK 3.0.0
> Flutter SDK 3.10.0
> flutter_map 3.2.0
> ```

Same exact as here (my flutter_map is 3.1.0 but I imagine that is what you meant).  Odd.  But I'll keep playing around with it on my end.  Thank you for the very quick responses!

**Comment by W2NJL** [comment] 2023-05-20 03:00
I just want to update this.  This is I should be clear, specifically on an iOS Emulator, with an iPhone 14 Pro Max, running iOS 16.4.

But the OverlayImage Zoom issue disappears when I downgraded back to Flutter 3.7.12.  It behaves exactly as I remember, zooming to whatever the max is and the overlay stays.

**Comment by JaffaKetchup** [comment] 2023-05-20 06:26
@W2NJL Are you running with Impeller? Could that be a cause of the problem?

**Comment by W2NJL** [comment] 2023-05-20 14:04
> @W2NJL Are you running with Impeller? Could that be a cause of the problem?

Thank you for asking - I have not experimented at with Impeller for rendering yet.  I could conversely try it (though I doubt that would help)?

**Comment by JaffaKetchup** [comment] 2023-05-20 14:19
AFAIK Flutter 3.10 has it enabled by default? If it isn't, try turning it on: not sure what will happen.

**Comment by W2NJL** [comment] 2023-05-20 14:29
> AFAIK Flutter 3.10 has it enabled by default? If it isn't, try turning it on: not sure what will happen.

I think you nailed it, Impeller has to be at least part of the culprit.  With my project running Flutter 3.7.12, I ran it with the impeller enable flag, and after compiling, I tried zooming in with an overlay and the app immediately crashed, with the following message:

Requested texture size exceeds maximum supported size of (8669, 9058)

**Comment by JaffaKetchup** [comment] 2023-05-20 15:00
Can you disable Impeller on 3.10? I think there's a build flag available.

**Comment by W2NJL** [comment] 2023-05-20 15:05
> Can you disable Impeller on 3.10? I think there's a build flag available.

That fixes it.  I updated back to 3.10.1, and ran flutter run --no-enable-impeller and on iOS the overlay can zoom in all the way normally again.

**Comment by JaffaKetchup** [comment] 2023-05-20 15:53
Better make a bug report then, and direct them here. Happy to do it if you don't have time, but a video would be appreciated I guess.

**Comment by W2NJL** [comment] 2023-05-20 16:11
> Better make a bug report then, and direct them here. Happy to do it if you don't have time, but a video would be appreciated I guess.

I just made two videos, one with Impeller enabled and zooming into the overlay:
[](https://vimeo.com/828616405?share=copy)

And one with Impeller disabled, and the same zoom:
[](https://vimeo.com/828616262?share=copy)

Should I just make a bug report on the main Flutter repo?  I can definitely do so.  Thank you so much for working with me on this.

**Comment by JaffaKetchup** [comment] 2023-05-20 16:24
Yeah, post a bug on the Flutter repo with those two videos and "[Impeller]" in the title, mentioning flutter_map and a reproducible example (they'll likely reject the issue if you don't include an MRE). Add a link to it here and I'll go and follow it :)

**Comment by W2NJL** [comment] 2023-05-20 16:42
> Yeah, post a bug on the Flutter repo with those two videos and "[Impeller]" in the title, mentioning flutter_map and a reproducible example (they'll likely reject the issue if you don't include an MRE). Add a link to it here and I'll go and follow it :)

Just opened this, thank you!  https://github.com/flutter/flutter/issues/127272

**Comment by JaffaKetchup** [comment] 2023-05-20 16:42
Great!

**Comment by JaffaKetchup** [comment] 2023-05-31 06:39
Should be fixed by https://github.com/flutter/flutter/issues/127272.

**Closed by JaffaKetchup** 2023-05-31 06:39 UTC
Labels: bug, non-fatal
