### ISSUE TITLE
[FEATURE] Implement tilt function

### ISSUE THREAD

**Issue by alequilesl** [fleaflet/flutter_map#1643] opened 2023-09-07 05:19 UTC
### What do you want implemented?

implement the tilt function in the MapController class to make the map more visual

### What other alternatives are available?

Use Transform.rotate to rotate the widget, but the markers rotate and scale too

### Severity

Minimum: Not required for my use

**Comment by JaffaKetchup** [comment] 2023-09-07 05:53
Duplicate of #1268

**Closed** 2023-09-07 05:54 UTC
Labels: duplicate, feature
