### ISSUE TITLE
Lot of connection failures

### ISSUE THREAD

**Issue by giohappy** [fleaflet/flutter_map#654] opened 2020-06-15 15:55 UTC
This happens very frequently while panning and/or zooming. Does it happen only to me?

![image](https://user-images.githubusercontent.com/571129/84679296-6faba680-af31-11ea-8e8f-5914901b5b7f.png)

**Comment by HugoHeneault** [comment] 2020-06-19 07:52
Have a look over here: https://stackoverflow.com/questions/55879550/how-to-fix-httpexception-connection-closed-before-full-header-was-received

Are you using android q? ;)

**Comment by giohappy** [comment] 2020-06-19 07:58
Thanks, I'll give it a try. 
I don't have a physical device running Android Q but I hope this issue only affects emulators, otherwise it would be a serious blicker.

**Comment by giohappy** [comment] 2020-06-22 22:01
Physical device seems ok but with Android 9 API 28 on x86 emulator (Windows 10) I still get the exceptions, which make any subsequent request fail.

Don't you face this error on emulatora @HugoHeneault?

**Comment by ThexXTURBOXx** [comment] 2020-09-07 18:49
I have the exact same issue, but not only in the emulator.
I also face this problem on my physical device (Xiaomi Mi 9T Pro), which is also running on Android Q.

**Comment by ThexXTURBOXx** [comment] 2021-03-22 12:39
One can work around this issue by just retrying the requests again and again. As a very naive workaround, one could do something like this in the `http` library: https://github.com/Femtopedia/http/commit/4478a7a4204cff39c026dcb46ebbd7225c34eaa7

**Attention: This could maybe lead to unexpected behavior in some cases and this is definetly not the correct way to handle this issue, but it works for now**

**Comment by ThexXTURBOXx** [comment] 2021-04-29 06:23
* Comment to remove the stale label *

**Comment by kengu** [comment] 2021-04-29 07:18
This is not an issue with flutter_map, a lot of similar errors are reported in both flutter generally, see 

* https://github.com/flutter/flutter/issues/41573
* https://github.com/flutter/flutter/issues/58676
* https://stackoverflow.com/questions/57058412/connection-closed-before-full-header-was-received

Some alternatives to try out
* use `NetworkTileProvider` which uses [NetworkImageWithRetry](https://pub.dev/packages/flutter_image) internally
* roll your own CustomTileProvider with something like [Cached network image](https://pub.dev/packages/cached_network_image)

I've experienced this problem many times in plain other flutter projects, and dart also (server-side). I believe the root cause is deep in dart core. Hence, I don't think we is able to solve the root problem on our side. Closing.

**Closed by kengu** 2021-04-29 07:18 UTC

**Comment by ThexXTURBOXx** [comment] 2021-05-03 09:35
@kengu Actually, I think, it can be fixed since the new version of HTTP (namely 0.13.2) is released. There, a new HTTPClient was added, which is called `RetryClient`. It retries failed requests up to a maximum amount of tries.

Since my workaround of just trying to retry failed requests worked, the new `RetryClient` should most likely also work. I will do some more testing and report back.
