### ISSUE TITLE
[BUG] MacOS: Mouse scrolling doesn't zoom

### ISSUE THREAD

**Issue by rohanjariwala03** [fleaflet/flutter_map#1414] opened 2022-12-06 20:06 UTC
### What is the bug?

- In macOS when I tried to zoom in or out with the mouse scrolling button then it's not working.
- It's moving the up, down, left, right.
- Whereas the same class working when I tried to run on Web.
 

### What is the expected behaviour?

- When I scroll it should be zoom in or out same as web.

### How can we reproduce this issue?

```dart
- Launch app in any MacOs and scroll with the help of mouse.
```

### Can you provide any other information?

Below video is of MacOs which have issue while scrolling

https://user-images.githubusercontent.com/34390549/206010996-e0b71e55-c451-4322-b236-83d5ed01ff3f.mov

Below Video is for Web where with the help of scrolling it's working

https://user-images.githubusercontent.com/34390549/206011598-c6c12dd1-6038-4ced-bf76-3f9c9a17a89c.mov

### Platforms Affected

MacOS

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by JosefWN** [comment] 2022-12-07 13:14
Probably related to the general issues with https://github.com/fleaflet/flutter_map/issues/1354, i.e. something to do with the new multitouch support on macOS introduced in the latest major version of Flutter.

For debugging purposes: what if you disable the pinch to zoom gesture?

**Comment by JaffaKetchup** [comment] 2022-12-20 18:20
(verified)

**Comment by JaffaKetchup** [comment] 2023-05-20 17:51
This needs to be re-evaluated.
@rohanjariwala03 When you get a moment, can you re-evaluate whether this issue is still applicable in the 'master' branch with the latest Flutter 3.10 version?
Thanks!

**Comment by JosefWN** [comment] 2023-05-21 12:03
Tried to connect a mouse with a scroll wheel today on `flutter_map` v4 running on Ventura 13.4 and this seems to be working. It zooms, and it zooms on the pointer location.

**Comment by JaffaKetchup** [comment] 2023-05-21 12:06
@JosefWN Thanks, we'll close this for now. Does this also change the status of #1354?

**Closed** 2023-05-21 12:06 UTC
Labels: bug, non-fatal

**Comment by JosefWN** [comment] 2023-05-21 12:15
Unfortunately not, https://github.com/fleaflet/flutter_map/issues/1354 is still an issue :(

**Comment by rohanjariwala03** [comment] 2023-05-23 13:25
@JosefWN @JaffaKetchup , Thanks, It's working as expected.

**Comment by rohanjariwala03** [comment] 2023-05-23 13:34
Unfortunately, No, still it's an issue.

**Comment by JosefWN** [comment] 2023-05-23 13:42
> Unfortunately, still it's an issue.

I think you will need to provide a minimal reproducible code example then, so we can more easily debug/reproduce the issue.

**Comment by rohanjariwala03** [comment] 2023-05-23 18:54
> Can you make it a complete example that actually runs? Then I can try again with that exact code.

I've updated my last comment. (https://github.com/fleaflet/flutter_map/issues/1414#issuecomment-1559536827)

**Comment by JosefWN** [comment] 2023-05-23 23:13
That code also works for me with a mouse, using the scroll wheel to zoom in/out. Did you try running the example code you sent me as well (after the edit), just to see 100% that it's not something else related to your code.

```yaml
environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"
```

```bash
flutter --version                                                                                   
Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (7 days ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1
```

MacOS: 13.4

This is my environment, what does yours look like? If you are behind on anything, could you try upgrading?

**Comment by rohanjariwala03** [comment] 2023-05-24 13:20
Here is the `flutter --version` output

![image](https://github.com/fleaflet/flutter_map/assets/34390549/a7e15fca-62e7-4b5a-96be-cbd712de9b50)

Tried with following mouse....

<img src="https://github.com/fleaflet/flutter_map/assets/34390549/a42b8590-2472-445b-a7f9-c51d7174cd4b" width="200">
<img src="https://github.com/fleaflet/flutter_map/assets/34390549/78fbf2c1-8144-42a4-9501-9f7cb187fe4a" width="200">

Just for clarification zoom out and zoom in is working perfectly in web app and windows app and just having issue with MacOS.

**Comment by JaffaKetchup** [comment] 2023-05-24 13:45
Can you verify in some way that you're depending on the 'master' branch? See https://stackoverflow.com/a/72446556/11846040.

**Comment by rohanjariwala03** [comment] 2023-05-24 13:49
Preview of `flutter pub deps` for flutter_map

![Screenshot 2023-05-24 at 9 48 48 AM](https://github.com/fleaflet/flutter_map/assets/34390549/f2d3e661-8fdb-4693-83b9-4e128f5d6efa)

**Comment by JaffaKetchup** [comment] 2023-05-24 13:53
@rohanjariwala03 Can you try depending on 'master' instead?

**Comment by JosefWN** [comment] 2023-05-24 14:15
> EDIT: @JosefWN Not sure how this would work on v4? I thought it is currently only fixed on master, but maybe it was fixed a while ago.

Without a deeper knowledge of the mouse/touch code, I think the mouse events are different from the touch events, and could possibly have been working for quite a while? But yes, this is what I have in my pubspec.yaml when I'm testing:
```yaml
dependencies:
  flutter_map: ^4.0.0
  # ...
```

```bash
flutter pub deps | grep flutter_map
├── flutter_map 4.0.0
```

> Just for clarification zoom out and zoom in with mouse is working perfectly in web app and windows app and just having issue with MacOS.

Yes, I'm running the app native on MacOS. Seems to be some specific triggering factor. For the Magic Mouse specifically I don't know if the gesture register as mouse two-finger touch (which is pan), that could potentially be an issue? But it should really work with the Logitech mouse.

@rohanjariwala03, what about your `environment` section of the pubspec.yaml? OS version?

**Comment by rohanjariwala03** [comment] 2023-05-24 14:21
I'm on the Mac M1 base as well. Don't know what's the potential issue with MacOs. 

**Environment** :
```
environment:
  sdk: '>=2.16.0'
  flutter: ">=3.10.0"
```

**Comment by rohanjariwala03** [comment] 2023-05-24 14:24
Okay, Thanks for help. I've tried with MacBook M2 chip and it's working. So, I think there is some settings issue with My MacMini. 
@JosefWN and @JaffaKetchup  , Thanks for solving the issue.

Appreciated.

**Comment by JosefWN** [comment] 2023-05-24 14:28
I figured the OS comes bundled with a set of drivers which might be slightly different from one version to another (especially major versions, if you are running a MacOS version below 13), and that there could be a potential issue/incompatibility in Flutter with a specific OS version.

What if you bump to this?
```yaml
environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"
```

I'm charging a Magic Mouse now to test with, will try in both release and debug with both mice.

**Comment by JosefWN** [comment] 2023-05-24 14:30
> Okay, Thanks for help. I've tried with MacBook M2 chip and it's working. So, I think there is some settings issue with My MacMini.

Ah, cool. Something that could help: Try re-installing Flutter so you have a fresh install. Rarely, during upgrades the install can get a bit borked for some reason, has happened to me once in 3-4 years, and I've seen others encounter odd issues which were helped by a re-install.

**Comment by rohanjariwala03** [comment] 2023-05-24 14:31
Even though I'm using following environment, still that's an issue.

```
environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"
```

For your context, Magic Mouse still not work in MacOS for zoom in and out. But it work's with Web.

**Comment by rohanjariwala03** [comment] 2023-05-24 14:32
> encounter

Will try to do so. Thanks

**Comment by JosefWN** [comment] 2023-05-24 15:02
Scrolling with the Magic Mouse in a native app seems to be interpreted as two-finger touch, which is pan. Not sure that we should do anything about this though, this is in line with native behavior (Apple Maps works the same way for example).

Running on web it will probably work since the touch API:s seem to be less mature there, so the two-finger swipe translates into a scroll, which is interpreted as zoom in/out in Google Maps using Chrome for example.
